{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "017ad192",
   "metadata": {},
   "source": [
    "# Dynamic Programming"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6dea2e12",
   "metadata": {},
   "source": [
    "* Bir target değeri vardır. \n",
    "* Target değerine en az eleman kullanarak elde edilmeye çalışılır."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6068564b",
   "metadata": {},
   "source": [
    "# Prim Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "566602c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*** PRIM's Algoritması ***\n",
      "Birinci Düğüm:0 - ikinci Düğüm:2, Arasındaki en kısa uzaklık:5\n",
      "Birinci Düğüm:2 - ikinci Düğüm:3, Arasındaki en kısa uzaklık:1\n",
      "Birinci Düğüm:3 - ikinci Düğüm:4, Arasındaki en kısa uzaklık:1\n",
      "Birinci Düğüm:4 - ikinci Düğüm:1, Arasındaki en kısa uzaklık:2\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "*** PRIM's Algoritması *** \n",
    "\n",
    "* Cycle oluşturmayacak \n",
    "* En kısa yol seçilmeli\n",
    "\n",
    "1. Başlangıç düğümünü seç\n",
    "2. Yakın komşularına bak en kısa yol olana ve daha önce gidilmemiş olana git.\n",
    "3. Artık yeni birleşim yerlerini bir kapsam olarak düşünüp 2. adıma dön. Eğer bütün düğümler ziyaret edilmişse bitir. \n",
    "\"\"\"\n",
    "\n",
    "INF = 999999\n",
    "\n",
    "N = 5\n",
    "\n",
    "# Komşuluk Matrisi \n",
    "G = [[0, 19, 5, 0, 0],\n",
    "     [19, 0, 5, 9, 2],\n",
    "     [5, 5, 0, 1, 6],\n",
    "     [0, 9, 1, 0, 1],\n",
    "     [0, 2, 6, 1, 0]]\n",
    "\n",
    "selected_node = [0,0,0,0,0]\n",
    "counter = 0 \n",
    "\n",
    "# ilk düğüm yani başlangıç düğümü için ziyaret edildi yapılır. \n",
    "selected_node[0] = True\n",
    "print(\"*** PRIM's Algoritması ***\")\n",
    "\n",
    "# Şimdi de aşağıdaki kod parçasında her bir düğüm için diğer düğümlere bakılıp min uzaklık ve ziyaret edilme durumuna göre \n",
    "# bir seçip yapılacaktır.\n",
    "while counter < N -1:\n",
    "    minimum = INF\n",
    "    a = 0\n",
    "    b = 0\n",
    "    for m in range(N):\n",
    "        # Ziyaret edilmiş bir düğüm için diğer düğümlerle olan uzaklıklarına bakıyoruz.\n",
    "        if selected_node[m]:\n",
    "            # Bu kısımda her bir düğüm için en kısa ve ziyaret edilmemiş düğümü bulmaya çalışıyoruz. Yani her düğüm için\n",
    "            # yaptığımızdan dolayı bir kapsam olarak görüyoruz. \n",
    "            for n in range(N):\n",
    "                # Eğer node seçilmediyse ve komşuluk matrisinde uzunluğu 0 değilse (0 da False, diğer sayılarda True döner)\n",
    "                if ((not selected_node[n]) and G[m][n]):\n",
    "                    if G[m][n] < minimum:\n",
    "                        minimum = G[m][n]\n",
    "                        a = m\n",
    "                        b = n\n",
    "    print(f\"Birinci Düğüm:{a} - ikinci Düğüm:{b}, Arasındaki en kısa uzaklık:{minimum}\")\n",
    "    # Yeni gidilen düğümü ziyaret edilmiş olarak işaretledik. Birinci düğüm zaten işaretleniyor ve kodda ona göre seçiliyor.\n",
    "    selected_node[b] = True\n",
    "    counter +=1\n",
    "                    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6d8c96c",
   "metadata": {},
   "source": [
    "# Kruskal's Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "0e353288",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Edges in the constructed MST\n",
      "2 -- 3 == 4\n",
      "0 -- 3 == 5\n",
      "0 -- 1 == 10\n",
      "Minimum Spanning Tree 19\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "*** Kruskal ***\n",
    "\n",
    "1. Baştan sona en her kenar ayrı ayrı yazılır.\n",
    "2. Kenarlara göre küçükten büyüğe sıralanır. \n",
    "3. Ek kısa kenardan uzuna doğru edge'ler eklenmeye başlar.\n",
    "4. Eğer düğümler bir cycle oluşturuyorsa op edge kabul edilmez devam edilir.\n",
    "\"\"\"\n",
    "\n",
    "class Graph:\n",
    " \n",
    "    def __init__(self, vertices):\n",
    "        self.V = vertices  # No. of vertices\n",
    "        self.graph = []\n",
    "        # to store graph\n",
    " \n",
    "    # function to add an edge to graph\n",
    "    def addEdge(self, u, v, w):\n",
    "        self.graph.append([u, v, w])\n",
    " \n",
    "    # Parent'ını çağır\n",
    "    def find(self, parent, i):\n",
    "        if parent[i] != i:\n",
    "            parent[i] = self.find(parent, parent[i])\n",
    "        return parent[i]\n",
    " \n",
    "\n",
    "    def union(self, parent, rank, x, y):\n",
    "\n",
    "        # rank değerine göre parentlarını değiştiriyoruz.\n",
    "        if rank[x] < rank[y]:\n",
    "            parent[x] = y\n",
    "        elif rank[x] > rank[y]:\n",
    "            parent[y] = x\n",
    " \n",
    "        else:\n",
    "            parent[y] = x\n",
    "            rank[x] += 1\n",
    " \n",
    "\n",
    "    def KruskalMST(self):\n",
    " \n",
    "        result = []  \n",
    "        i = 0\n",
    "        e = 0\n",
    "        # Ağırlıkları küçükten büyüğe sıralıyoruz\n",
    "        self.graph = sorted(self.graph,\n",
    "                            key=lambda item: item[2])\n",
    " \n",
    "        parent = []\n",
    "        rank = []\n",
    " \n",
    "        # Create V subsets with single elements\n",
    "        for node in range(self.V):\n",
    "            parent.append(node)\n",
    "            rank.append(0)\n",
    " \n",
    "        # Number of edges to be taken is less than to V-1\n",
    "        while e < self.V - 1:\n",
    " \n",
    "            # graph'ı küçükten büyüğe sıraladığımız için 1. yanı en kısa olan edge'i seçiyoruz ve i değerini bir arttırıyoruz.\n",
    "            u, v, w = self.graph[i]\n",
    "            i = i + 1\n",
    "            x = self.find(parent, u)\n",
    "            y = self.find(parent, v)\n",
    " \n",
    "            # Cycle oluşturmaması için bir kontrol yapıyoruz\n",
    "            if x != y:\n",
    "                e = e + 1\n",
    "                result.append([u, v, w])\n",
    "                self.union(parent, rank, x, y)\n",
    " \n",
    "        minimumCost = 0\n",
    "        print(\"Edges in the constructed MST\")\n",
    "        for u, v, weight in result:\n",
    "            minimumCost += weight\n",
    "            print(\"%d -- %d == %d\" % (u, v, weight))\n",
    "        print(\"Minimum Spanning Tree\", minimumCost)\n",
    " \n",
    " \n",
    "# Driver's code\n",
    "if __name__ == '__main__':\n",
    "    g = Graph(4)\n",
    "    g.addEdge(0, 1, 10)\n",
    "    g.addEdge(0, 2, 6)\n",
    "    g.addEdge(0, 3, 5)\n",
    "    g.addEdge(1, 3, 15)\n",
    "    g.addEdge(2, 3, 4)\n",
    " \n",
    "    # Function call\n",
    "    g.KruskalMST()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4bd615d9",
   "metadata": {},
   "source": [
    "## My Code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "200bcdfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "First node: 2 - second Node: 3 = Distance: 4\n",
      "First node: 0 - second Node: 3 = Distance: 5\n",
      "First node: 0 - second Node: 1 = Distance: 10\n",
      "Minimum Cost: 19\n"
     ]
    }
   ],
   "source": [
    "class Graph():\n",
    "    \n",
    "    def __init__(self, vertices):\n",
    "        self.V = vertices\n",
    "        self.graph = []\n",
    "        \n",
    "    def my_add_edge(self, u,v,w):\n",
    "        self.graph.append([u,v,w])\n",
    "        \n",
    "    def my_union(self, parent, rank, x, y):\n",
    "        \n",
    "        if rank[x] > rank[y]:\n",
    "            parent[y] = x\n",
    "        elif rank[x] < rank[y]:\n",
    "            parent[x] = y\n",
    "        else:\n",
    "            parent[y] = x\n",
    "            rank[x] +=1\n",
    "            \n",
    "    def my_find(self, parent, i):\n",
    "        if parent[i] != i:\n",
    "            self.my_find(parent, parent[i])\n",
    "        return parent[i]\n",
    "            \n",
    "    def my_kruskal(self, start_node):\n",
    "        result = []\n",
    "        i = e = 0\n",
    "        \n",
    "        # Ağırlıklarına göre sıralama\n",
    "        self.graph =  sorted(self.graph, key = lambda item: item[2])\n",
    "        \n",
    "        parent = []\n",
    "        rank = []\n",
    "        \n",
    "        # İlk başta hepsinin parent ı kendisi rank durumları da 0 dır.\n",
    "        for node in range(self.V):\n",
    "            parent.append(node)\n",
    "            rank.append(0)\n",
    "        \n",
    "        \n",
    "        # Her bir değer için kontrol ve en kısa yolu bulma\n",
    "        while e < self.V -1:\n",
    "            u,v,w = self.graph[i]\n",
    "            i += 1\n",
    "            x = self.my_find(parent, u)\n",
    "            y = self.my_find(parent, v)\n",
    "\n",
    "            if x != y:\n",
    "                e +=1\n",
    "                result.append([u,v,w])\n",
    "                self.my_union(parent, rank, x , y)\n",
    "            \n",
    "        \n",
    "        # Print the outputs\n",
    "        min_cost = 0\n",
    "        for u,v, weight in result:\n",
    "            min_cost = min_cost + weight\n",
    "            print(f\"First node: {u} - second Node: {v} = Distance: {weight}\")\n",
    "        print(\"Minimum Cost:\", min_cost)\n",
    "            \n",
    "        \n",
    "        \n",
    "\n",
    "g = Graph(4)\n",
    "g.my_add_edge(0, 1, 10)\n",
    "g.my_add_edge(0, 2, 6)\n",
    "g.my_add_edge(0, 3, 5)\n",
    "g.my_add_edge(1, 3, 15)\n",
    "g.my_add_edge(2, 3, 4)\n",
    "\n",
    "g.my_kruskal(0)\n",
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fffbce34",
   "metadata": {},
   "source": [
    "# Dijkstra’s Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "9c2a7948",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Vertex \t Distance from Source\n",
      "0 \t\t 0\n",
      "1 \t\t 4\n",
      "2 \t\t 12\n",
      "3 \t\t 19\n",
      "4 \t\t 21\n",
      "5 \t\t 11\n",
      "6 \t\t 9\n",
      "7 \t\t 8\n",
      "8 \t\t 14\n"
     ]
    }
   ],
   "source": [
    "class Graph():\n",
    " \n",
    "    def __init__(self, vertices):\n",
    "        self.V = vertices\n",
    "        self.graph = [[0 for column in range(vertices)]\n",
    "                      for row in range(vertices)]\n",
    " \n",
    "\n",
    "    def minDistance(self, dist, sptSet):\n",
    " \n",
    "        # Min a sonsuz bir sayı koyulur\n",
    "        min = 1e7\n",
    " \n",
    "        # En küçük uzaklığı bulma \n",
    "        for v in range(self.V):\n",
    "            if dist[v] < min and sptSet[v] == False:\n",
    "                min = dist[v]\n",
    "                min_index = v\n",
    " \n",
    "        return min_index\n",
    " \n",
    "    # Function that implements Dijkstra's single source\n",
    "    # shortest path algorithm for a graph represented\n",
    "    # using adjacency matrix representation\n",
    "    def dijkstra(self, src):\n",
    "        \n",
    "        # Uzaklıkları ilk başta hepsi için sonsuz yapıyoruz 1e7 = 10^7\n",
    "        dist = [1e7] * self.V\n",
    "        # Başlangıç düğümümüzün uzaklığını 0 yapıyoruz\n",
    "        dist[src] = 0\n",
    "        # Bütün ziyaret edilme durumları false yapılır.\n",
    "        sptSet = [False] * self.V\n",
    " \n",
    "        for count in range(self.V):\n",
    " \n",
    "            u = self.minDistance(dist, sptSet)\n",
    "            \n",
    "            # Seçilen düğüm ziyaret edilmiş olarak işaretlenir. \n",
    "            sptSet[u] = True\n",
    " \n",
    "            # Eğer seçilen değer küçükşe durumu\n",
    "            for v in range(self.V):\n",
    "                if (self.graph[u][v] > 0 and\n",
    "                   sptSet[v] == False and\n",
    "                   dist[v] > dist[u] + self.graph[u][v]):\n",
    "                    dist[v] = dist[u] + self.graph[u][v]\n",
    " \n",
    "        print(\"Vertex \\t Distance from Source\")\n",
    "        for node in range(self.V):\n",
    "            print(node, \"\\t\\t\", dist[node])\n",
    "\n",
    "    \n",
    "g = Graph(9)\n",
    "g.graph = [[0, 4, 0, 0, 0, 0, 0, 8, 0],\n",
    "           [4, 0, 8, 0, 0, 0, 0, 11, 0],\n",
    "           [0, 8, 0, 7, 0, 4, 0, 0, 2],\n",
    "           [0, 0, 7, 0, 9, 14, 0, 0, 0],\n",
    "           [0, 0, 0, 9, 0, 10, 0, 0, 0],\n",
    "           [0, 0, 4, 14, 10, 0, 2, 0, 0],\n",
    "           [0, 0, 0, 0, 0, 2, 0, 1, 6],\n",
    "           [8, 11, 0, 0, 0, 0, 1, 0, 7],\n",
    "           [0, 0, 2, 0, 0, 0, 6, 7, 0]]\n",
    " \n",
    "g.dijkstra(0)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c7a6965",
   "metadata": {},
   "source": [
    "## My Code "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "e1a1da43",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 - 0\n",
      "1 - 4\n",
      "2 - 12\n",
      "3 - 19\n",
      "4 - 21\n",
      "5 - 11\n",
      "6 - 9\n",
      "7 - 8\n",
      "8 - 14\n"
     ]
    }
   ],
   "source": [
    "def my_min_distance(graph, dist, visited, vertices):\n",
    "    min_value = 1e7\n",
    "    \n",
    "    for num in range(vertices):\n",
    "        if dist[num] < min_value and visited[num] == False:\n",
    "            min_value = dist[num]\n",
    "            min_index = num\n",
    "    return min_index\n",
    "\n",
    "def my_dijkstra(start_node, vertices, graph):\n",
    "    \n",
    "    dist = [1e7] * vertices\n",
    "    visited = [False] * vertices\n",
    "    \n",
    "    dist[start_node] = 0\n",
    "    \n",
    "    for i in range(vertices):\n",
    "        u = my_min_distance(graph, dist, visited, vertices)\n",
    "        visited[u] = True\n",
    "        \n",
    "        for v in range(vertices):\n",
    "            if visited[v] == False and graph[u][v] > 0 and dist[v] > dist[u] + graph[u][v]:\n",
    "                dist[v] = dist[u] + graph[u][v]\n",
    "        \n",
    "    \n",
    "    for i in range(vertices):\n",
    "        print(f\"{i} - {dist[i]}\")\n",
    "        \n",
    "        \n",
    "# Run the code\n",
    "graph = [[0, 4, 0, 0, 0, 0, 0, 8, 0],\n",
    "           [4, 0, 8, 0, 0, 0, 0, 11, 0],\n",
    "           [0, 8, 0, 7, 0, 4, 0, 0, 2],\n",
    "           [0, 0, 7, 0, 9, 14, 0, 0, 0],\n",
    "           [0, 0, 0, 9, 0, 10, 0, 0, 0],\n",
    "           [0, 0, 4, 14, 10, 0, 2, 0, 0],\n",
    "           [0, 0, 0, 0, 0, 2, 0, 1, 6],\n",
    "           [8, 11, 0, 0, 0, 0, 1, 0, 7],\n",
    "           [0, 0, 2, 0, 0, 0, 6, 7, 0]]\n",
    "\n",
    "my_dijkstra(0, 9, graph)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "96adfbdc",
   "metadata": {},
   "source": [
    "# Boruvka's Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "988dafa7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Edge 0-3 with weight 5 included in MST\n",
      "Edge 0-1 with weight 10 included in MST\n",
      "Edge 2-3 with weight 4 included in MST\n",
      "Weight of MST is 19\n"
     ]
    }
   ],
   "source": [
    "from collections import defaultdict\n",
    " \n",
    "class Graph:\n",
    " \n",
    "    def __init__(self,vertices):\n",
    "        self.V= vertices \n",
    "        self.graph = [] \n",
    "  \n",
    "    def addEdge(self,u,v,w):\n",
    "        self.graph.append([u,v,w])\n",
    " \n",
    "    def find(self, parent, i):\n",
    "        if parent[i] != i:\n",
    "            self.find(parent, parent[i])\n",
    "        return parent[i]\n",
    " \n",
    "    def union(self, parent, rank, x, y):\n",
    "        xroot = self.find(parent, x)\n",
    "        yroot = self.find(parent, y)\n",
    " \n",
    "        # burada birleştirme işlemi yapıyoruz. Eğer rank olarak büyük olanın parentını az olan da alır\n",
    "        if rank[xroot] < rank[yroot]:\n",
    "            parent[xroot] = yroot\n",
    "        elif rank[xroot] > rank[yroot]:\n",
    "            parent[yroot] = xroot\n",
    " \n",
    "        else :\n",
    "            parent[yroot] = xroot\n",
    "            rank[xroot] += 1\n",
    " \n",
    "    # The main function to construct MST using Kruskal's algorithm\n",
    "    def boruvkaMST(self):\n",
    "        parent = []; rank = [];\n",
    " \n",
    "        cheapest =[]\n",
    " \n",
    "        numTrees = self.V\n",
    "        MSTweight = 0\n",
    " \n",
    "        for node in range(self.V):\n",
    "            parent.append(node)\n",
    "            rank.append(0)\n",
    "            cheapest =[-1] * self.V\n",
    "     \n",
    " \n",
    "        while numTrees > 1:\n",
    " \n",
    "            # Traverse through all edges and update\n",
    "               # cheapest of every component\n",
    "            for i in range(len(self.graph)):\n",
    " \n",
    "                # Find components (or sets) of two corners\n",
    "                # of current edge\n",
    "                u,v,w =  self.graph[i]\n",
    "                set1 = self.find(parent, u)\n",
    "                set2 = self.find(parent ,v)\n",
    " \n",
    "                if set1 != set2:    \n",
    "                     \n",
    "                    if cheapest[set1] == -1 or cheapest[set1][2] > w :\n",
    "                        cheapest[set1] = [u,v,w]\n",
    " \n",
    "                    if cheapest[set2] == -1 or cheapest[set2][2] > w :\n",
    "                        cheapest[set2] = [u,v,w]\n",
    " \n",
    "            for node in range(self.V):\n",
    " \n",
    "                #Check if cheapest for current set exists\n",
    "                if cheapest[node] != -1:\n",
    "                    u,v,w = cheapest[node]\n",
    "                    set1 = self.find(parent, u)\n",
    "                    set2 = self.find(parent ,v)\n",
    " \n",
    "                    if set1 != set2 :\n",
    "                        MSTweight += w\n",
    "                        self.union(parent, rank, set1, set2)\n",
    "                        print (\"Edge %d-%d with weight %d included in MST\" % (u,v,w))\n",
    "                        numTrees = numTrees - 1\n",
    "             \n",
    "            #reset cheapest array\n",
    "            cheapest =[-1] * self.V\n",
    " \n",
    "             \n",
    "        print (\"Weight of MST is %d\" % MSTweight)\n",
    "                           \n",
    " \n",
    "     \n",
    "g = Graph(4)\n",
    "g.addEdge(0, 1, 10)\n",
    "g.addEdge(0, 2, 6)\n",
    "g.addEdge(0, 3, 5)\n",
    "g.addEdge(1, 3, 15)\n",
    "g.addEdge(2, 3, 4)\n",
    " \n",
    "g.boruvkaMST()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e267c4ba",
   "metadata": {},
   "source": [
    "## My Code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "bcbbd8f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 - 3 -> 5\n",
      "0 - 1 -> 10\n",
      "0 - 2 -> 6\n"
     ]
    }
   ],
   "source": [
    "class Graph():\n",
    "    \n",
    "    def __init__(self, vertices):\n",
    "        self.V =vertices\n",
    "        self.graph = []\n",
    "        \n",
    "    def my_add_edge(self, u, v, w):\n",
    "        self.graph.append([u,v,w])\n",
    "    \n",
    "    # Find root\n",
    "    def find(self, parent, i):\n",
    "        if parent[i] != i:\n",
    "            self.find(parent, parent[i])\n",
    "        return parent[i]\n",
    "    \n",
    "    def my_union(self, parent, rank, x, y):\n",
    "        xroot = self.find(parent, x)\n",
    "        yroot = self.find(parent, y)\n",
    "        \n",
    "        if rank[xroot] > rank[yroot]:\n",
    "            parent[y] = x\n",
    "        elif rank[yroot] > rank[xroot]:\n",
    "            parent[x] = y\n",
    "        else:\n",
    "            parent[y] = x\n",
    "            rank[x] +=1\n",
    "            \n",
    "    def my_boruvka(self):\n",
    "        parent = []\n",
    "        rank = []\n",
    "        result = []\n",
    "        MSTweight = 0\n",
    "        e = 0\n",
    "        \n",
    "        for node in range(self.V):\n",
    "            parent.append(node)\n",
    "            rank.append(0)\n",
    "            result = [-1] * self.V\n",
    "            \n",
    "        while e < self.V - 1:\n",
    "            for i in range(self.V):\n",
    "                u,v,w = self.graph[i]\n",
    "                set_x = self.find(parent, u)\n",
    "                set_y = self.find(parent, v)\n",
    "                \n",
    "                if set_x != set_y:\n",
    "                    if result[set_x] == -1 or result[set_x][2] > w:\n",
    "                        result[set_x] = [u,v,w]\n",
    "                    if result[set_y] == -1 or result[set_y][2] > w:\n",
    "                        result[set_y] = [u,v,w]\n",
    "                        \n",
    "            for i in range(self.V):\n",
    "                \n",
    "                if result[i] != -1:\n",
    "                    u,v,w = result[i]\n",
    "                    set_x = self.find(parent, u)\n",
    "                    set_y = self.find(parent, v)\n",
    "                    \n",
    "                    if set_x != set_y:\n",
    "                        MSTweight += w\n",
    "                        self.my_union(parent, rank, set_x,set_y)\n",
    "                        print(f\"{u} - {v} -> {w}\")\n",
    "                        e +=1\n",
    "                        \n",
    "            result = [-1] * self.V\n",
    "                        \n",
    "                \n",
    "                \n",
    "    \n",
    "    \n",
    "g = Graph(4)\n",
    "g.my_add_edge(0, 1, 10)\n",
    "g.my_add_edge(0, 2, 6)\n",
    "g.my_add_edge(0, 3, 5)\n",
    "g.my_add_edge(1, 3, 15)\n",
    "g.my_add_edge(2, 3, 4)\n",
    " \n",
    "g.my_boruvka()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e5d74de",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
